### PR TITLE
Italian Language

### PR DESCRIPTION
**Pull request by Fastbyte01**
Added the italian translation and link to the italian translation

### CODE REVIEW

**Comment by clickwork-git** [comment]
Thank you very much! Grazie tanto!

**Comment by dignajar** [comment]
Hi @Fastbyte01 
I can accept this PR if only you compromise to translate all the official webpages of Bludit, because I can't provide to the users only a part of the sites in Italian.

The official sites are:
- https://www.bludit.com
- https://pro.bludit.com
- https://plugins.bludit.com
- https://themes.bludit.com
- https://docs.bludit.com (this is going to be only a part of the documentation, just some topics, I need to discuss with @clickwork-git these topics, but I remember was `GETTING STARTED`, `CONTENT`, `BLUDIT PRO`)

**Comment by Fastbyte01** [comment]
@dignajar No problem for the other translation, the pro homepage is already translated as you can see on my other pull request. A good thing that we can do is to add the links to the homepages when the translations are all ready, for now you can merge the translation and add the links to italian translations once they are all ready.

**Comment by Fastbyte01** [comment]
@dignajar If you see the others pull request now seems that remain only docs. In which way to proceed now? I have seen that some language have they "folder" with the translation of the documentation.

**Comment by dignajar** [comment]
@Fastbyte01 I going to check the PR.
About Documentation, let me work on it, and create the repository for you, with the parts interested to translate.

**Pull request merged**
